### ISSUE TITLE
order_stock_locations removed from solidus

### ISSUE THREAD

**Issue by ccarruitero** [solidusio-contrib/solidus_legacy_stock_system#6]
`OrderStockLocation` was removed from solidus since https://github.com/solidusio/solidus/commit/96a553dd63c2a9d32fa2e805094e9730b6ffe727#diff-434de9976fbb9c7d9358f1cb3d401019, causing builds with master for this gem to fail.

These are used in [stock/coordinator](https://github.com/solidusio-contrib/solidus_legacy_stock_system/blob/master/app/models/spree/stock/coordinator.rb#L41)

But in commit that removed the model, mention there was unable to create since 2.2.

So, I think we can just remove the references to that model too.

What do you think?

**Comment by mamhoff** [comment]
Since this is the *legacy* stock system, I believe we should actually move that model into this gem.

**Comment by jhawthorn** [comment]
Fixed by #7
